
from pathlib import Path
from typing import List, Optional
import shutil

try:
    from moviepy import ImageClip, AudioFileClip, concatenate_videoclips, concatenate_audioclips
    MOVIEPY_AVAILABLE = True
except ImportError:
    MOVIEPY_AVAILABLE = False


class VideoStitcher:
    def __init__(self, output_file: str):
        self.output_path = output_file
        if not MOVIEPY_AVAILABLE:
            raise ImportError("MoviePy not installed. Please install: pip install moviepy")

    def stitch(self, image_paths: List[Path], audio_map: List[List[Path]], resolution: str = '1080p'):
        """
        Stitch images and audio into a video.
        :param image_paths: List of paths to slide images.
        :param audio_map: List of Lists. audio_map[i] = [audio1, audio2] for image i.
        :param resolution: '720p', '1080p', or '4k'. Controls bitrate.
        """
        print(f"🎬 Stitching Video into {self.output_path}...")
        
        clips = []
        
        for i, img_path in enumerate(image_paths):
            if i >= len(audio_map):
                continue
                
            frame_audios = audio_map[i]
            
            # Create Audio Clip for this frame
            if not frame_audios:
                # Silence
                duration = 2
                audio_clip = None
            else:
                # Filter out empty/invalid files (generated by error handler)
                valid_audios = [a for a in frame_audios if a.exists() and a.stat().st_size > 500] 
                
                if not valid_audios:
                    duration = 2
                    audio_clip = None
                else:
                    audio_objs = [AudioFileClip(str(a)) for a in valid_audios]
                    audio_clip = concatenate_audioclips(audio_objs) if len(audio_objs) > 1 else audio_objs[0]
                    duration = audio_clip.duration
            
            # Create Video Clip
            video_clip = ImageClip(str(img_path)).with_duration(duration)
            if audio_clip:
                video_clip = video_clip.with_audio(audio_clip)
                
            clips.append(video_clip)
            
        if not clips:
            print("❌ No clips to stitch.")
            return

        final_video = concatenate_videoclips(clips)
        
        # Bitrate Logic
        is_4k = (resolution == '4k')
        audio_bitrate = '320k'
        video_bitrate = '50000k' if is_4k else '8000k' 
        preset = 'slow'
        
        print(f"⚙️  Encoding: {resolution} ({video_bitrate}), {audio_bitrate} audio, preset={preset}")
        
        final_video.write_videofile(
            self.output_path, 
            fps=24, 
            codec='libx264', 
            audio_codec='aac', 
            bitrate=video_bitrate,
            audio_bitrate=audio_bitrate,
            preset=preset,
            threads=4
        )
